# version: '3'

services:
  # Definição do kafka como serviço para ser utilizado pelo backend
  kafka:
    image: confluentinc/cp-kafka:latest 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9091:9091"
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  # Serviço de backend
  notification:
    # Configuração para construir o serviço a partir do contexto(diretório) do Dockerfile
    build:
      context: ./
    # Mapeamento de porta para acesso externo, porta 5000 do host para porta 5000 do contêiner
    ports:
      - "5000:5000"
    # Monta um volume para o serviço, útil para persistir dados de banco de dados, arquivos de log, etc.
    volumes:
      - notification_data:/notification/data
    depends_on:
      # Garante que o Kafka estará rodando antes do serviço iniciar
      - kafka
    # Comando para esperar o Kafka estar completamente disponível antes de iniciar o serviço, utilizando o script `wait-for-it.sh`
    command: ["./wait-for-it.sh", "-t", "30", "kafka:9092", "--", "npm", "run", "start:prod"]
    networks:
      - kafka-network

# Definição dos volumes no nível superior
volumes:
  # Define um volume nomeado para persistir os dados do serviço
  notification_data:

# Definição das redes para os serviços poderem se comunicar
networks:
  # Rede para comunicação entre os contêineres do Kafka e de notificação
  kafka-network:
    # Definição do driver da rede, sendo `bridge` o driver padrão, usado para comunicação entre contêineres em um mesmo host
    driver: bridge